### ISSUE TITLE
FR: Rename bardify to Bradify

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/bardify#1]
![brad-pitt-grooming-legend-2001](https://user-images.githubusercontent.com/7669885/42899990-9dbef3a8-8abf-11e8-8952-8088ff7f10df.jpg)

**Comment by jackmcdade** [comment]
![Naw](https://media.giphy.com/media/SLQ1lVTcRQ7XG/giphy.gif)

**Comment by jasonvarga** [comment]
[Danny, I told you that you're on timeout](https://github.com/statamic/v2-hub/issues/2072#issuecomment-405976055)

**Comment by dannyuk1982** [comment]
I dunno, I think you are missing out on my good ideas, hidden in between.... other ideas.
